# Generated by Django 3.2.9 on 2021-12-09 17:03

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0002_auto_20211208_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.RenameModel(
            old_name='ListingImages',
            new_name='ListingImage',
        ),
        migrations.RenameModel(
            old_name='ListingReviews',
            new_name='ListingReview',
        ),
        migrations.RenameModel(
            old_name='Neighborhoods',
            new_name='Neighborhood',
        ),
        migrations.RenameModel(
            old_name='ToolModels',
            new_name='ToolModel',
        ),
        migrations.RenameModel(
            old_name='ToolTypes',
            new_name='ToolType',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
